name: Link Activity to CMIP7
description: Register an activity for use in CMIP7
title: "Link Activity to CMIP7:"
labels: ['delta', 'activity', 'Review']
body:
  - type: dropdown
    id: activity
    attributes:
      multiple: true
      label: Activity
      description: |
        If your activity is not listed below, you must first register it in the [WCRP-constants repository](https://wcrp-cmip.github.io/WCRP-constants/activity/) after which it should appear in the dropdown below.
        
        <details>
        <summary>Existing entries</summary>
        
        **Currently registered in CMIP7:**
        
        
        </details>
      options:
        - "AERA-MIP"
        - "AerChemMIP"
        - "AerChemMIP2"
        - "C4MIP"
        - "CDRMIP"
        - "CERESMIP"
        - "CFMIP"
        - "CMIP"
        - "CORDEX"
        - "DAMIP"
        - "DCPP"
        - "FireMIP"
        - "FishMIP"
        - "GeoMIP"
        - "HighResMIP"
        - "IRRMIP"
        - "ISMIP7"
        - "LESFMIP"
        - "LMIP"
        - "LUMIP"
        - "LongRunMIP"
        - "MISOMIP2"
        - "MUMIP"
        - "MethaneMIP"
        - "NAHosMIP"
        - "OMIP"
        - "PMIP"
        - "PPEMIP"
        - "RAMIP"
        - "RAMIP "
        - "RFMIP"
        - "SIMIP"
        - "SOFIAMIP"
        - "SP-MIP"
        - "ScenarioMIP"
        - "TBIMIP"
        - "TIPMIP"
        - "VolMIP"
        - "WhatIfMIP"
        - "no-value"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata [for internal use only]

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
