name: 'Add/Modify: Experiment'
description: 'Type: experiment'
title: 'Add/Modify: Experiment: <enter item name>'
labels:
- delta
- experiment
body:
-   type: markdown
    attributes:
        value: Please fill in the form below.
-   id: name
    attributes:
        label: Experiment ID
        description: There are rules for constructing acceptable experiment names which
            can be found in this <a href="https://docs.google.com/document/d/1CeMkNsE74v1wD4x48lKJ_uixWu8DsKgAa9fpD9q94aM/edit?tab=t.0">guidance
            document</a>.
    validations:
        required: true
    type: input
-   id: title
    attributes:
        label: Experiment Title
        description: A short phrase that can help in interpreting the unique
            experiment_id’s. As examples, the CMIP6 titles are listed
            [here](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html)
            in the third column labeled “experiments”.
    validations:
        required: true
    type: input
-   id: description
    attributes:
        label: Description
        description: Provide all information not included elsewhere in this form that
            would be required to correctly configure the model and impose the
            experiment conditions. Include a description of the experiment, links to
            any appropriate references and indicate similarities to CMIP6
            experiments. Please also include details of forcing differences relative
            to the parent experiment.
    validations:
        required: true
    type: textarea
-   id: activity
    attributes:
        label: MIP / Activity ID (registered)
        description: The MIP / activity owning the experiment.
        # This would ideally be a reference object from <a href=https://wcrp-cmip.github.io/WCRP-universe/activity/>
        #    https://wcrp-cmip.github.io/WCRP-universe/activity/ </a>. '
        options:
            - AerChemMIP
            - C4MIP
            - CFMIP
            - DAMIP
            - DCPP
            - GeoMIP
            - LMIP
            - PMIP
            - RFMIP
            - ScenarioMIP
    validations:
        required: true
    type: dropdown
-   id: activity_other
    attributes:
        label: MIP / Activity ID (unregistered)
        description: Please enter your MIP / activity ID below if it does not appear in the list above. Leave blank otherwise.
    type: input
    validations:
        required: false
-   type: markdown
    attributes:
        value: "*Notes on Source types*"
-   type: markdown
    attributes:
        value: |
            Source type codes representing different model component defined in the next two sections have the following descriptions
            * AER  : Aerosol treatment in an atmospheric model where concentrations are calculated based on emissions, transformation, and removal processes (rather than being prescribed or omitted entirely)
            * AGCM : Atmospheric general circulation model run with prescribed ocean surface conditions and usually a model of the land surface
            * AOGCM : Coupled atmosphere-ocean global climate model, additionally including explicit representation of at least the land and sea ice
            * BGC  : Biogeochemistry model component that at the very least accounts for carbon reservoirs and fluxes in the atmosphere, terrestrial biosphere, and ocean
            * CHEM : Chemistry treatment in an atmospheric model that calculates atmospheric oxidant concentrations (including at least ozone), rather than prescribing them
            * ISM  : Ice-sheet model that includes ice-flow
            * LAND : Land model run uncoupled from the atmosphere
            * OGCM : Ocean general circulation model run uncoupled from an AGCM but, usually including a sea-ice model
            * RAD  : Radiation component of an atmospheric model run 'offline'
            * SLAB : Slab-ocean used with an AGCM in representing the atmosphere-ocean coupled system
       
-   id: required_model_realms
    attributes:
        label: Source type codes for required Model Components
        description: Components that must be included in models when running this
            experiment. See note 15 in https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/Papers/CMIP6_global_attributes_filenames_CVs_v6.2.7.pdf for full descriptions
        options:
        -   label: AER
        -   label: AGCM
        -   label: AOGCM
        -   label: BGC
        -   label: CHEM
        -   label: ISM
        -   label: LAND
        -   label: OGCM
        -   label: RAD
        -   label: SLAB
    validations:
        required: false
    type: checkboxes
-   id: model_realms
    attributes:
        label: Source type codes for additional allowed model components
        description: Components that may be included in models when running this
            experiment. See note 15 in https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/Papers/CMIP6_global_attributes_filenames_CVs_v6.2.7.pdf for full description
        options:
        -   label: AER
        -   label: AGCM
        -   label: AOGCM
        -   label: BGC
        -   label: CHEM
        -   label: ISM
        -   label: LAND
        -   label: OGCM
        -   label: RAD
        -   label: SLAB
    validations:
        required: false
    type: checkboxes
-   id: parent_experiment
    attributes:
        label: Parent Experiment ID (Registered)
        description: The ID of the experiment providing the initial conditions. If not
            initialised from another CMIP7 experiment select "no parent"
            #'A reference object from <a href=https://wcrp-cmip.github.io/CMIP7_CVs/experiment/>
            # https://wcrp-cmip.github.io/CMIP7_CVs/experiment/ </a>. '
        options:
        - 1pctco2
        - 1pctco2-bgc
        - 1pctco2-rad
        - abrupt-0p5co2
        - abrupt-2xco2
        - abrupt-4xco2
        - amip
        - amip-p4k
        - amip-piforcing
        - esm-flat10-cdr
        - esm-flat10-zec
        - esm-hist
        - esm-picontrol
        - g7-15k-sai
        - high-scenario (esm-scen7-h or scen7-hc)
        - hist-aer
        - hist-ghg
        - hist-nat
        - hist-piaer
        - hist-pislcf
        - historical
        - initialised-prediction-2025-2036
        - land-hist
        - ligabrupt
        - low-scenario (esm-scen7-l or scen7-lc)
        - medium-low-scenario (esm-scen7-ml and scen7-mlc)
        - medium-scenario-and-extension (esm-scen7-m or scen7-mc)
        - piclim-4xco2
        - piclim-aer
        - piclim-anthro
        - piclim-ch4
        - piclim-control
        - piclim-hc
        - piclim-histaer
        - piclim-histall
        - piclim-n2o
        - piclim-nox
        - piclim-so2
        - piclim-voc
        - picontrol
        - sspx-slcf
        - very-low-scenario-low-overshoot (esm-scen7-vllo and scen7-vlloc)  
        - very-low-scenario-high-overshoot (esm-scen7-vlho and scen7-vlhoc)  
        - no-parent
    validations:
        required: true
    type: dropdown
-   id: parent_experiment_other
    attributes:
        label: Parent Experiment ID (unregistered)
        description: The ID of the experiment providing the initial conditions / forcings, where it has not already been registered.
    type: input
    validations:
        required: false
-   id: sub_experiment
    attributes:
        label: Sub-experiment
        description: The list of sub-experiment IDs where relevant. For most experiments this will be "none"
    validations:
        required: true
    type: input
-   id: tier
    attributes:
        label: Tier
        description: How essential is the experiment to the primary scientific goals of
            the activity? 1=absolutely essential, 2=of major value, 3=of lesser
            value
    validations:
        required: true
    type: input
-   id: start
    attributes:
        label: Start Date
        description: For experiments initialized on a particular historical date, enter
            that date in the form YYYY-MM-DD. If a set of sub-experiments are
            initialized at different times, list all the start times requested. For
            example, for an historical simulation initialized at the beginning of
            1850, enter “1850-01-01”. For a set of DCPP “prediction” runs, enter all
            dates of the first full forecast/hindcast year (e.g., 1960, 1970, 1980,
            1990, 2000, 2010). If there is no specific start date please leave this
            field blank
    validations:
        required: false
    type: input
-   id: branch-date
    attributes:
      label: Branch Date
      description: For experiments initialized from a non-arbitrary point in a parent
        experiment, enter the branch date in the parent, i.e. the point at which
        initial conditions should be taken. For example, “2022-01-01” should be
        entered for an experiment initialized from the end of the historical
        experiment and extending into the future. If there is no parent
        experiment please leave this field blank.
    validations:
      required: false
    type: input
-   id: min-number-yrs-per-sim
    attributes:
      label: (Minimum) Number of Years
      description: For most experiments this will be the actual length of the desired
        simulation. For example, “172” would be specified for a run initialized
        in 1850-01-01 and extending to 2022-01-01.
    validations:
      required: false
    type: input
