name: 'Add/Modify: Experiment'
description: 'Type: experiment'
title: 'Add/Modify: Experiment: <enter item name>'
labels:
- delta
- experiment
body:
-   type: markdown
    attributes:
        value: Please fill in the form below.
-   id: name
    attributes:
        label: Experiment ID
        description: A string containing alphanumeric characters or "-" (i.e. no underscores,
            spaces or other characters). Please keep this string below 14 characters
            in length if possible.
    validations:
        required: true
    type: input
-   id: description
    attributes:
        label: Description
        description: Include a description of the experiment, links to any appropriate
            references and indicate similarities to CMIP6 experiments. Please also include details 
            of forcing differences relative to the parent experiment
    validations:
        required: true
    type: textarea
-   id: activity
    attributes:
        label: MIP / Activity ID (registered)
        description: The MIP / activity owning the experiment.
        # This would ideally be a reference object from <a href=https://wcrp-cmip.github.io/WCRP-universe/activity/>
        #    https://wcrp-cmip.github.io/WCRP-universe/activity/ </a>. '
        options:
        - aerchemmip
        - c4mip
        - cfmip
        - cmip
        - damip
        - dcpp
        - geomip
        - lmip
        - pmip
        - rfmip
        - scenariomip
    validations:
        required: true
    type: dropdown
-   id: activity_other
    attributes:
        label: MIP / Activity ID (unregistered)
        description: Please enter your MIP / activity ID below if it does not appear in the list above. Leave blank otherwise.
    type: input
    validations:
        required: false
-   id: parent_activity
    attributes:
        label: Parent Activity ID (registered)
        description: The MIP / Activity ID of the parent experiment
        #'A reference object from <a href=https://wcrp-cmip.github.io/WCRP-universe/activity/>
        #    https://wcrp-cmip.github.io/WCRP-universe/activity/ </a>. '
        options:
        - aerchemmip
        - c4mip
        - cfmip
        - cmip
        - damip
        - dcpp
        - geomip
        - lmip
        - pmip
        - rfmip
        - scenariomip
    validations:
        required: true
    type: dropdown
-   id: parent_activity_other
    attributes:
        label: Parent Activity ID (unregistered)
        description: Please enter the MIP / Activity ID of the parent experiment if not listed 
            in the dropdown above. Leave blank otherwise.
        # New Parent Activity For new values only, please register them
        #    in the relevant area.
    type: input
    validations:
        required: false
-   type: markdown
    attributes:
        value: "*Notes on model components*"
-   type: markdown
    attributes:
        value: |
            Model component codes defined in the following sections below have the following descriptions
            * aer  : Aerosol treatment in an atmospheric model where concentrations are calculated based on emissions, transformation, and removal processes (rather than being prescribed or omitted entirely)
            * agcm : Atmospheric general circulation model run with prescribed ocean surface conditions and usually a model of the land surface
            * aogcm : Coupled atmosphere-ocean global climate model, additionally including explicit representation of at least the land and sea ice
            * bgc  : Biogeochemistry model component that at the very least accounts for carbon reservoirs and fluxes in the atmosphere, terrestrial biosphere, and ocean
            * chem : Chemistry treatment in an atmospheric model that calculates atmospheric oxidant concentrations (including at least ozone), rather than prescribing them
            * ism  : Ice-sheet model that includes ice-flow
            * land : Land model run uncoupled from the atmosphere
            * ogcm : Ocean general circulation model run uncoupled from an AGCM but, usually including a sea-ice model
            * rad  : Radiation component of an atmospheric model run 'offline'
            * slab : Slab-ocean used with an AGCM in representing the atmosphere-ocean coupled system
       
-   id: required_model_realms
    attributes:
        label: Required Model Components
        description: Components that must be included in models when running this
            experiment. See note 15 in https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/Papers/CMIP6_global_attributes_filenames_CVs_v6.2.7.pdf for full descriptions
        options:
        -   label: aer
        -   label: agcm
        -   label: aogcm
        -   label: bgc
        -   label: chem
        -   label: ism
        -   label: land
        -   label: ogcm
        -   label: rad
        -   label: slab
    validations:
        required: false
    type: checkboxes
-   id: model_realms
    attributes:
        label: Allowed Model Components
        description: Components that must be included in models when running this
            experiment. See note 15 in https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/Papers/CMIP6_global_attributes_filenames_CVs_v6.2.7.pdf for full description
        options:
        -   label: aer
        -   label: agcm
        -   label: aogcm
        -   label: bgc
        -   label: chem
        -   label: ism
        -   label: land
        -   label: ogcm
        -   label: rad
        -   label: slab
    validations:
        required: false
    type: checkboxes
-   id: parent_experiment
    attributes:
        label: Parent Experiment ID (Registered)
        description: The ID of the experiment providing the initial conditions / forcings
        #'A reference object from <a href=https://wcrp-cmip.github.io/CMIP7_CVs/experiment/>
        # https://wcrp-cmip.github.io/CMIP7_CVs/experiment/ </a>. '
        options:
        - 1pctco2
        - 1pctco2-bgc
        - 1pctco2-rad
        - abrupt-0p5co2
        - abrupt-2xco2
        - abrupt-4xco2
        - amip
        - amip-p4k
        - amip-piforcing
        - esm-flat10-cdr
        - esm-flat10-zec
        - esm-hist
        - esm-picontrol
        - g7-15k-sai
        - high-scenario
        - hist-aer
        - hist-ghg
        - hist-nat
        - hist-piaer
        - hist-pislcf
        - historical
        - initialised-prediction-2025-2036
        - land-hist
        - ligabrupt
        - low-overshoot-scenario
        - low-scenario
        - medium-scenario-and-extension
        - piclim-4xco2
        - piclim-aer
        - piclim-anthro
        - piclim-ch4
        - piclim-control
        - piclim-hc
        - piclim-histaer
        - piclim-histall
        - piclim-n2o
        - piclim-nox
        - piclim-so2
        - piclim-voc
        - picontrol
        - sspx-slcf
        - very-low-scenario
    validations:
        required: true
    type: dropdown
-   id: parent_experiment_other
    attributes:
        label: Parent Experiment ID (unregistered)
        description: The ID of the experiment providing the initial conditions / forcings, where it has not already been registered.
    type: input
    validations:
        required: false
-   id: sub_experiment
    attributes:
        label: Sub-experiment
        description: The Sub-experiment ID where relevant. For most experiments this will be "none"
    validations:
        required: true
    type: input
-   id: tier
    attributes:
        label: Tier
        description: Tier level of the experiment (1, 2, or 3)
    validations:
        required: true
    type: input
-   id: end
    attributes:
        label: End Date
        description: The point at which the simulations should finish (e.g., 2020-01-01)
    validations:
        required: false
    type: input
-   id: min-number-yrs-per-sim
    attributes:
        label: Minimum Number of Years
        description: Minimum number of years for the simulation
    validations:
        required: false
    type: input
-   id: start
    attributes:
        label: Start Date
        description: Start date of the simulation (e.g., 1850-01-01)
    validations:
        required: true
    type: input
