name: 'Add/Modify: Experiment'
description: 'Type: experiment'
title: 'Add/Modify: Experiment: <Type experiment name here>'
projects: ["WCRP-CMIP/4"]  # Updated to link to org project 4
labels:
    - delta
    - experiment
    - Review
body:

-   type: markdown
    attributes:
        value: |
            ####
            ## Generic Experiment information

            Please fill in the information below. 

    
-   id: label
    attributes:
        label: Experiment ID
        description: |
            There are rules for constructing acceptable experiment names which
            can be found in this <a href="https://doi.org/10.5281/zenodo.14929768">guidance document</a>.
            
            Note: This name must be unique across all experiments.
        placeholder: 'e.g., piClim-CH4, hist-GHG, amip-p4k'
    validations:
        required: true
    type: input
-   id: long_label
    attributes:
        label: Experiment Title
        description: |
            A short phrase that can help in interpreting the unique
            experiment_id’s. 
            
            As examples, the CMIP6 titles are listed [here](https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html) in the third column labeled “experiments”.
        placeholder: 'e.g., AMIP plus 4K sea surface temperature'
    validations:
        required: true
    type: input
-   id: description
    attributes:
        label: Description
        description: |
            Please provide:
             >      1. Detailed experiment configuration
             >      2. Required model settings
             >      3. Experiment conditions
             >      4. Links to relevant references
             >      5. Similarities to CMIP6 experiments
             >      6. Forcing differences from parent experiment
        placeholder: 'Describe the experiment configuration, conditions, and requirements...'
    validations:
        required: true
    type: textarea
-   id: activity
    attributes:
        label: MIP / Activity ID (registered)
        description: |
            The MIP / activity owning the experiment
            
            Please select a parent from the list below. 
        options:
            - "Custom Activity: specify below"
            - AerChemMIP
            - C4MIP
            - CFMIP
            - DAMIP
            - DCPP
            - GeoMIP
            - LMIP
            - PMIP
            - RFMIP
            - ScenarioMIP
        
    validations:
        required: true
    type: dropdown
-   id: activity_other
    attributes:
        label: MIP / Activity ID (unregistered)
        description: Please enter your MIP / activity ID below if it does not appear in the list above. Leave blank otherwise.
    type: input
    validations:
        required: false

        
-   type: markdown
    attributes:
        value: |
            ####
            ## Parent information and Tier
                    
-   id: parent_experiment
    attributes:
        label: Parent Experiment
        description: |
            Select the experiment that provides initial conditions. Expected ScenarioMIP experiments are listed in the table below.
            If the parent experiment id required is one of these scenarios please enter this text in the custom parent box below.
            | Scenario | emissions driven | emissions driven extension | concentration driven | concentration driven extension |
            | :--- | :---: | :---: | :---: | :---: | 
            | high | `esm-scen7-h` | `esm-scen7-h-ext` | `scen7-hc` | `scen7-hc-ext` |
            | high overshoot extensions  |   | `esm-scen7-h-ext-os` |  | `scen7-hc-ext-os` |
            | medium | `esm-scen7-m` | `esm-scen7-m-ext` | `scen7-mc` | `scen7-mc-ext` |
            | medium-low | `esm-scen7-ml` | `esm-scen7-ml-ext` | `scen7-mlc` | `scen7-mlc-ext` |
            | low | `esm-scen7-l` | `esm-scen7-l-ext` | `scen7-lc` | `scen7-lc-ext` |
            | very low, low overshoot | `esm-scen7-vllo` | `esm-scen7-vllo-ext` | `scen7-vlloc` | `scen7-vlloc-ext` |
            | very low, high overshoot | `esm-scen7-vlho` | `esm-scen7-vlho-ext` | `scen7-vlhoc` | `scen7-vlhoc-ext` |

            Please select a parent from the list below. 
            
        options:
        - "Custom Parent: specify below"
        - no-parent
        - 1pctCO2
        - 1pctCO2-bgc
        - 1pctCO2-rad
        - abrupt-0p5CO2
        - abrupt-2xCO2
        - abrupt-4xCO2
        - amip
        - amip-p4k
        - amip-piForcing
        - esm-flat10-cdr
        - esm-flat10-zec
        - esm-hist
        - esm-piControl
        - G7-15K-SAI
        - high-scenario
        - hist-aer
        - hist-GHG
        - hist-nat
        - hist-piAer
        - hist-piSLCF
        - historical
        - initialised-prediction-2025-2036
        - land-hist
        - LIGabrupt
        - low-scenario
        - medium-low-scenario
        - medium-scenario-and-extension
        - piClim-4xCO2
        - piClim-aer
        - piClim-anthro
        - piClim-CH4
        - piClim-control
        - piClim-HC
        - piClim-histaer
        - piClim-histall
        - piClim-N2O
        - piClim-NOx
        - piClim-SO2
        - piClim-VOC
        - piControl
        - SSPX-SLCF
        - very-low-scenario-low-overshoot
        - very-low-scenario-high-overshoot
        
    validations:
        required: true
    type: dropdown
-   id: parent_experiment_other
    attributes:
        label: Custom Parent Experiment
        description: Only fill this if your parent experiment is not in the list above.
        placeholder: 'e.g., new-experiment-2024'
    validations:
        required: false
    type: input
-   id: sub_experiment
    attributes:
        label: Sub-experiment
        description: The list of sub-experiment IDs where relevant. For most experiments this will be "none"
        placeholder: 'e.g., "none"'
    validations:
        required: true
    type: input
-   id: tier
    attributes:
        label: Priority Tier
        description: |
            Select the experiment's priority level:
            
                - Tier 1: Essential to primary scientific goals
                - Tier 2: Major scientific value
                - Tier 3: Useful but lower priority
        options:
            - '1'
            - '2'
            - '3'
    validations:
        required: true
    type: dropdown

            


-   type: markdown
    attributes:
        value: |
            ####
            ## Model Component Requirements
            
            Select the required and optional model components for this experiment:

                
                
                > * AER  : Aerosol treatment in an atmospheric model where concentrations are calculated based on emissions, transformation, and removal processes (rather than being prescribed or omitted entirely)
                > * AGCM : Atmospheric general circulation model run with prescribed ocean surface conditions and usually a model of the land surface
                > * AOGCM : Coupled atmosphere-ocean global climate model, additionally including explicit representation of at least the land and sea ice
                > * BGC  : Biogeochemistry model component that at the very least accounts for carbon reservoirs and fluxes in the atmosphere, terrestrial biosphere, and ocean
                > * CHEM : Chemistry treatment in an atmospheric model that calculates atmospheric oxidant concentrations (including at least ozone), rather than prescribing them
                > * ISM  : Ice-sheet model that includes ice-flow
                > * LAND : Land model run uncoupled from the atmosphere
                > * OGCM : Ocean general circulation model run uncoupled from an AGCM but, usually including a sea-ice model
                > * RAD  : Radiation component of an atmospheric model run 'offline'
                > * SLAB : Slab-ocean used with an AGCM in representing the atmosphere-ocean coupled system
                    
-   id: required_model_realms
    attributes:
        label: Source type codes for required model components
        description: |
            Components that must be included in models when running this experiment. 
            See note 15 in https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/Papers/CMIP6_global_attributes_filenames_CVs_v6.2.7.pdf for full descriptions
            
            * Select Multiple * 
            
        options:
            -  AER
            -  AGCM
            -  AOGCM
            -  BGC
            -  CHEM
            -  ISM
            -  LAND
            -  OGCM
            -  RAD
            -  SLAB
        multiple: true
    validations:
        required: false
    type: dropdown
-   id: model_realms
    attributes:
        label: Source type codes for additional allowed model components
        description: |
            Components that may be included in models when running this experiment in addition to the required components listed above. 
            See note 15 in https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/Papers/CMIP6_global_attributes_filenames_CVs_v6.2.7.pdf for full description

            * Select Multiple * 
            
        options:
            -  AER
            -  AGCM
            -  AOGCM
            -  BGC
            -  CHEM
            -  ISM
            -  LAND
            -  OGCM
            -  RAD
            -  SLAB
        multiple: true
    validations:
        required: false
    type: dropdown

-   type: markdown
    attributes:
        value: |
            ####
            ## Experiment duration, start and end
            Some additional information on the experiment
            

-   id: start
    attributes:
        label: Start Date
        description: |
            For experiments initialized on a particular historical date, enter
            that date in the form YYYY-MM-DD. 
            
                If a set of sub-experiments are
                initialized at different times, list all the start times requested.
            
                - For example, for an historical simulation initialized at the beginning of
                1850, enter “1850-01-01”. 
                - For a set of DCPP “prediction” runs, enter all
                dates of the first full forecast/hindcast year (e.g., 1960, 1970, 1980,
                1990, 2000, 2010). 
                - If there is no specific start date please enter the word `none`
        placeholder: 'e.g., 1850-01-01 or 1960,1970,1980'
    validations:
        required: false
    type: input
# -   id: branch-date
#     attributes:
#       label: Branch Date
#       description: |
#         For experiments initialized from a non-arbitrary point in a parent
#         experiment, enter the branch date in the parent,i.e. the point at which
#         initial conditions should be taken. 
            
#             - For example, “2022-01-01” should be
#             entered for an experiment initialized from the end of the historical
#             experiment and extending into the future. 
#             - If there is no parent
#             experiment please leave this field blank.
#       placeholder: 'e.g., 2022-01-01'
#     validations:
#       required: false
#     type: input
-   id: min-number-yrs-per-sim
    attributes:
      label: (Minimum) Number of Years
      description: |
          For most experiments this will be the actual length of the desired
          simulation.
              
              Calculation : (end_year - start_year + 1)
              - For example, “172” would be specified for a run initialized
              in 1850-01-01 and extending to 2022-01-01.
      placeholder: 'e.g., 172'
    validations:
      required: true
    type: input



-   type: markdown
    attributes:
        value: |
            ####
            ## Issue Handling Metadata

            The following options are only here such that the github actions know what to do with the information provided above. 

            In almost all cases, these do not require to be changed. 



-   id: issue_category
    type: dropdown
    attributes:
        label: "Issue Type"
        #   description: "This is pre-set and cannot be changed."
        options:
            - "experiment"
        default: 0
    validations:
        required: true

-   id: issue_kind
    type: dropdown
    attributes:
        label: "Issue Kind"
        options:
            - "new"
            - "modify"
        default: 0
    validations:
        required: true  
