name: "Add/Modify: Experiment"
description: "Type: experiment"
title: "Add/Modify: Experiment: <Type experiment name here>"
labels: ['delta', 'experiment', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ####
        ## Generic Experiment information
        
        Please fill in the information below.

  - type: input
    id: label
    attributes:
      label: Experiment ID
      description: |
        There are rules for constructing acceptable experiment names which can be found in this guidance document (https://doi.org/10.5281/zenodo.14929768).
        
        Note: This name must be unique across all experiments.
      placeholder: "e.g., piClim-CH4, hist-GHG, amip-p4k"
    validations:
      required: true

  - type: input
    id: long_label
    attributes:
      label: Experiment Title
      description: |
        A short phrase that can help in interpreting the unique experiment IDs.
        
        As examples, the CMIP6 titles are listed at https://wcrp-cmip.github.io/CMIP6_CVs/docs/CMIP6_experiment_id.html in the third column labeled experiments.
      placeholder: "e.g., AMIP plus 4K sea surface temperature"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please provide:
         >      1. Detailed experiment configuration
         >      2. Required model settings
         >      3. Experiment conditions
         >      4. Links to relevant references
         >      5. Similarities to CMIP6 experiments
         >      6. Forcing differences from parent experiment
      placeholder: "Describe the experiment configuration conditions and requirements..."
    validations:
      required: true

  - type: dropdown
    id: activity
    attributes:
      label: MIP / Activity ID (registered)
      description: |
        The MIP / activity owning the experiment
        
        Please select a parent from the list below. Note: phases are not considered separate activies.
      options:
        - "AerChemMIP"
        - "C4MIP"
        - "CFMIP"
        - "CMIP"
        - "DAMIP"
        - "DCPP"
        - "GeoMIP"
        - "LMIP"
        - "PMIP"
        - "RFMIP"
        - "ScenarioMIP"
    validations:
      required: true

  - type: input
    id: activity_other
    attributes:
      label: MIP / Activity ID (unregistered)
      description: |
        Please enter your MIP / activity ID below if it does not appear in the list above. Leave blank otherwise.

  - type: markdown
    attributes:
      value: |
        ####
        ## Parent information and Tier

  - type: dropdown
    id: parent_experiment
    attributes:
      label: Parent Experiment
      description: |
        Select the experiment that provides initial conditions.
        Please note that scenarioMIP experiment names are under discussion and are likely to change
        
        Please select a parent from the list below.
      options:
        - "Custom Parent: specify in 'Parent experiment other' field"
        - "no-parent"
        - "1pctCO2-bgc"
        - "1pctCO2-rad"
        - "1pctCO2"
        - "abrupt-0p5CO2"
        - "abrupt-0p5xCO2"
        - "abrupt-127k"
        - "abrupt-2xCO2"
        - "abrupt-4xCO2-1950"
        - "abrupt-4xCO2"
        - "amip-m4K"
        - "amip-p4K-SST-rad"
        - "amip-p4K-SST-turb"
        - "amip-p4K"
        - "amip-piForcing"
        - "amip"
        - "control-1950"
        - "dcppB-forecast-cmip6"
        - "esm-flat10-cdr"
        - "esm-flat10-zec"
        - "esm-flat10"
        - "esm-hist"
        - "esm-piControl"
        - "esm-up2p0-gwl2p0"
        - "esm-up2p0"
        - "G7-1p5K-SAI"
        - "highres-yr2020"
        - "highresSST-p2K-pat"
        - "highresSST-p4K-pat"
        - "highresSST-p4k-uni"
        - "highresSST-present"
        - "hist-1950"
        - "hist-aer"
        - "hist-GHG"
        - "hist-irr"
        - "hist-nat"
        - "hist-noFire"
        - "hist-noirr"
        - "hist-piAer"
        - "hist-piAQ"
        - "hist-piSLCF"
        - "historical"
        - "Initialised-prediction-2025-2036"
        - "land-hist"
        - "LIGabrupt"
        - "piClim-2xBVOC"
        - "piClim-2xDMSpPMOA"
        - "piClim-2xdust"
        - "piClim-2xfire"
        - "piClim-2xss"
        - "piClim-2xWet"
        - "piClim-4xCO2"
        - "piClim-aer"
        - "piClim-anthro"
        - "piClim-AQ"
        - "piClim-BC"
        - "piClim-CH4"
        - "piClim-control"
        - "piClim-HC"
        - "piClim-histaer"
        - "piClim-histall"
        - "piClim-N2O"
        - "piClim-NH3"
        - "piClim-NOx"
        - "piClim-O3"
        - "piClim-OC"
        - "piClim-ODS"
        - "piClim-p4K"
        - "piClim-SO2"
        - "piClim-VOC"
        - "piControl"
        - "spinup-1950"
        - "SSPX-SLCF"
    validations:
      required: true

  - type: input
    id: parent_experiment_other
    attributes:
      label: Custom Parent Experiment
      description: Only fill this if your parent experiment is not in the list above.
      placeholder: "e.g., new-experiment-2024"

  - type: input
    id: sub_experiment
    attributes:
      label: Sub-experiment
      description: |
        The list of sub-excleperiment IDs where relevant. For most experiments this will be none
      placeholder: "e.g., none"
    validations:
      required: true

  - type: dropdown
    id: tier
    attributes:
      label: Priority Tier
      description: |
        Select the experiment's priority level:
        
            - Tier 1: Essential to primary scientific goals
            - Tier 2: Major scientific value
            - Tier 3: Useful but lower priority
      options:
        - "Tier 1"
        - "Tier 2"
        - "Tier 3"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ####
        ## Model Component Requirements
        
        Select the required and optional model components for this experiment:
        
            
            
            > * AER  : Aerosol treatment in an atmospheric model where concentrations are calculated based on emissions, transformation, and removal processes (rather than being prescribed or omitted entirely)
            > * AGCM : Atmospheric general circulation model run with prescribed ocean surface conditions and usually a model of the land surface
            > * AOGCM : Coupled atmosphere-ocean global climate model, additionally including explicit representation of at least the land and sea ice
            > * BGC  : Biogeochemistry model component that at the very least accounts for carbon reservoirs and fluxes in the atmosphere, terrestrial biosphere, and ocean
            > * CHEM : Chemistry treatment in an atmospheric model that calculates atmospheric oxidant concentrations (including at least ozone), rather than prescribing them
            > * ISM  : Ice-sheet model that includes ice-flow
            > * LAND : Land model run uncoupled from the atmosphere
            > * OGCM : Ocean general circulation model run uncoupled from an AGCM but, usually including a sea-ice model
            > * RAD  : Radiation component of an atmospheric model run offline
            > * SLAB : Slab-ocean used with an AGCM in representing the atmosphere-ocean coupled system

  - type: dropdown
    id: required_model_realms
    attributes:
      multiple: true
      label: Source type codes for required model components
      description: |
        Components that must be included in models when running this experiment.
        See note 15 in https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/Papers/CMIP6_global_attributes_filenames_CVs_v6.2.7.pdf for full descriptions
        
        * Select Multiple *
      options:
        - "AER"
        - "AGCM"
        - "AOGCM"
        - "BGC"
        - "CHEM"
        - "gridded_insitu"
        - "ISM"
        - "LAND"
        - "OGCM"
        - "RAD"
        - "reanalysis"
        - "satellite_blended"
        - "satellite_retrieval"
        - "SLAB"

  - type: dropdown
    id: model_realms
    attributes:
      multiple: true
      label: Source type codes for additional allowed model components
      description: |
        Components that may be included in models when running this experiment in addition to the required components listed above.
        See note 15 in https://wcrp-cmip.github.io/WGCM_Infrastructure_Panel/Papers/CMIP6_global_attributes_filenames_CVs_v6.2.7.pdf for full description
        
        * Select Multiple *
      options:
        - "AER"
        - "AGCM"
        - "AOGCM"
        - "BGC"
        - "CHEM"
        - "gridded_insitu"
        - "ISM"
        - "LAND"
        - "OGCM"
        - "RAD"
        - "reanalysis"
        - "satellite_blended"
        - "satellite_retrieval"
        - "SLAB"

  - type: markdown
    attributes:
      value: |
        ####
        ## Experiment duration, start and end
        Some additional information on the experiment

  - type: input
    id: start
    attributes:
      label: Start Date
      description: |
        For experiments initialized on a particular historical date, enter that date in the form YYYY-MM-DD.
        
            If a set of sub-experiments are initialized at different times, list all the start times requested.
        
            - For example, for an historical simulation initialized at the beginning of 1850, enter 1850-01-01.
            - For a set of DCPP prediction runs, enter all dates of the first full forecast/hindcast year (e.g., 1960, 1970, 1980, 1990, 2000, 2010).
            - If there is no specific start date please enter the word none
      placeholder: "e.g., 1850-01-01 or 1960,1970,1980"

  - type: input
    id: min-number-yrs-per-sim
    attributes:
      label: (Minimum) Number of Years
      description: |
        For most experiments this will be the actual length of the desired simulation.
        
        Calculation : (end_year - start_year + 1)
        - For example, 172 would be specified for a run initialized in 1850-01-01 and extending to 2022-01-01.
      placeholder: "e.g., 172"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ####
        ## Issue Handling Metadata
        
        The following options are only here such that the github actions know what to do with the information provided above.
        
        In almost all cases, these do not require to be changed.

  - type: dropdown
    id: issue_category
    attributes:
      label: Issue Type
      description: This is pre-set and cannot be changed.
      options:
      default: 0
    validations:
      required: true

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
      default: 0
    validations:
      required: true
