name: "Add/Modify: Frequency"
description: Add frequency to CMIP7 CVs
title: "Add/Modify: Frequency: <Type frequency name here>"
labels: ['delta', 'frequency', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        This form appends the following frequency into the permitted CMIP7 Controlled Vocabularies list.
        
        The permitted set of values are defined in the [WCRP universal constants repo](https://wcrp-cmip.github.io/WCRP-universe/frequency/). If your item is missing please [register here first](https://github.com/WCRP-CMIP/WCRP-universe/issues/new?template=frequency.yml) and wait a day after it has been confirmed for this script to be remade.

  - type: dropdown
    id: frequency
    attributes:
      multiple: true
      label: Frequency
      description: Select the frequencies to add to CMIP7
      options:
        - "1hr"
        - "1hrCM"
        - "1hrPt"
        - "3hr"
        - "3hrPt"
        - "6hr"
        - "6hrPt"
        - "day"
        - "dec"
        - "fx"
        - "mon"
        - "monC"
        - "monPt"
        - "subhrPt"
        - "yr"
        - "yrPt"
    validations:
      required: true
