name: General Issue
description: Report a general issue, bug, or request
title: "Issue: <Brief description here>"
labels: ['cmip7', 'general']
body:
  - type: markdown
    attributes:
      value: |
        ## General Issue Report
        
        Please provide details about your issue, bug report, or feature request.

  - type: dropdown
    id: issue_type
    attributes:
      label: Issue Type
      description: What kind of issue are you reporting?
      options:
        - "Bug Report"
        - "Feature Request"
        - "Documentation Issue"
        - "Data Quality Issue"
        - "Process Improvement"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: affected_areas
    attributes:
      multiple: true
      label: Affected Areas
      description: |
        Which parts of WCRP-universe does this issue affect?
        
        *Select multiple if applicable*
      options:
        - "Controlled Vocabularies (CVs)"
        - "Documentation"
        - "GitHub Actions/Workflows"
        - "Data Files"
        - "Scripts/Tools"
        - "Issue Templates"
        - "General Repository Structure"
        - "All/Multiple Areas"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Provide a clear and detailed description of the issue.
        
        For bugs: What happened? What did you expect to happen?
        For features: What would you like to see added/changed?
      placeholder: "Describe your issue in detail...\n\nInclude any relevant context, examples, or use cases."
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected/Desired Behavior
      description: What should happen instead? What would you like to see?
      placeholder: "The system should..."

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to Reproduce (for bugs)
      description: If reporting a bug provide step-by-step instructions to reproduce the issue.
      placeholder: "1. Go to...\n2. Click on...\n3. See error..."

  - type: markdown
    attributes:
      value: |
        ## Metadata

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How urgent is this issue?
      options:
        - "Critical - Blocking work"
        - "High - Important issue"
        - "Medium - Should be addressed"
        - "Low - Nice to fix"
      default: 2
    validations:
      required: true

  - type: dropdown
    id: help_needed
    attributes:
      multiple: true
      label: Help Needed
      description: Do you need help with this issue?
      options:
        - "I can work on this myself"
        - "I need help implementing a solution"
        - "I'm just reporting this issue"
