name: Link Resolution to CMIP7
description: Register a resolution for use in CMIP7
title: "Link Resolution to CMIP7:"
labels: ['delta', 'resolution', 'Review']
body:
  - type: dropdown
    id: native_nominal_resolution
    attributes:
      multiple: true
      label: Resolution
      description: |
        If your resolution is not listed below, you must first register it in the [WCRP-constants repository](https://github.com/WCRP-CMIP/WCRP-constants/issues/new?template=resolution.yml) after which it should appear in the dropdown below.
        
        <details>
        <summary>Currently registered in CMIP7</summary>
        
        - 0.5 km
        - 1 km
        - 10 km
        - 100 km
        - 1000 km
        - 10000 km
        - 1x1 degree
        - 2.5 km
        - 25 km
        - 250 km
        - 2500 km
        - 5 km
        - 50 km
        - 500 km
        - 5000 km
        
        </details>
      options:
        - "0.5 km"
        - "1 km"
        - "10 km"
        - "100 km"
        - "1000 km"
        - "10000 km"
        - "1x1 degree"
        - "2.5 km"
        - "25 km"
        - "250 km"
        - "2500 km"
        - "5 km"
        - "50 km"
        - "500 km"
        - "5000 km"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        
        
        ## Issue Handling Metadata [For internal use only]

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
