name: "New Review submission : Resolution"
description: Add resolution to CMIP7 CVs
title: "New Review submission : Resolution:"
labels: ['delta', 'resolution', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        This form appends the following resolution into the permitted CMIP7 Controlled Vocabularies list.
        
        The permitted set of values are defined in the [WCRP constants repo](https://wcrp-cmip.github.io/WCRP-constants/resolution/). If your item is missing please [register here first](https://github.com/WCRP-CMIP/WCRP-constants/issues/new?template=resolution.yml) and wait a day after it has been confirmed for this script to be remade.

  - type: dropdown
    id: native_nominal_resolution
    attributes:
      multiple: true
      label: Resolution
      description: Select the resolutions to add to CMIP7
      options:
        - "0.5 km"
        - "1 km"
        - "10 km"
        - "100 km"
        - "1000 km"
        - "10000 km"
        - "1x1 degree"
        - "2.5 km"
        - "25 km"
        - "250 km"
        - "2500 km"
        - "5 km"
        - "50 km"
        - "500 km"
        - "5000 km"
    validations:
      required: true
