name: Link Resolution to CMIP7
description: Register a resolution for use in CMIP7
title: "Link Resolution to CMIP7:"
labels: ['delta', 'resolution', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Link Resolution to CMIP7
        
        Select resolutions from WCRP-constants to make available in CMIP7.
        
        Resolutions are initially defined in the [WCRP-constants repository](https://github.com/WCRP-CMIP/WCRP-constants). You can view existing resolutions at https://wcrp-cmip.github.io/WCRP-constants/resolution/
        
        **If your resolution is not listed below**, you must first [register it in WCRP-constants](https://github.com/WCRP-CMIP/WCRP-constants/issues/new?template=resolution.yml) and wait for it to be approved before linking it here.
        
        Once your resolution exists in WCRP-constants, use this form to make it available for use in CMIP7.
        
        ---
        
        **Currently registered in CMIP7:**
        

  - type: dropdown
    id: native_nominal_resolution
    attributes:
      multiple: true
      label: Resolution
      description: Select the resolutions to add to CMIP7.
      options:
        - "0.5 km"
        - "1 km"
        - "10 km"
        - "100 km"
        - "1000 km"
        - "10000 km"
        - "1x1 degree"
        - "2.5 km"
        - "25 km"
        - "250 km"
        - "2500 km"
        - "5 km"
        - "50 km"
        - "500 km"
        - "5000 km"
    validations:
      required: true

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
