name: "New Review submission : Scientific Domain"
description: Add scientific domain to CMIP7 CVs
title: "New Review submission : Scientific Domain:"
labels: ['delta', 'scientific_domain', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        This form appends the following scientific domain into the permitted CMIP7 Controlled Vocabularies list.
        
        The permitted set of values are defined in the [WCRP constants repo](https://wcrp-cmip.github.io/WCRP-constants/scientific_domain/). If your item is missing please [register here first](https://github.com/WCRP-CMIP/WCRP-constants/issues/new?template=scientific_domain.yml) and wait a day after it has been confirmed for this script to be remade.

  - type: dropdown
    id: realm
    attributes:
      multiple: true
      label: Scientific Domain
      description: Select the scientific domains to add to CMIP7
      options:
        - "aerosol"
        - "atmosphere"
        - "atmospheric_chemistry"
        - "land_ice"
        - "land_surface"
        - "ocean"
        - "ocean_biogeochemistry"
        - "sea_ice"
    validations:
      required: true

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
