name: Link Scientific Domain to CMIP7
description: Register a scientific domain (realm) for use in CMIP7
title: "Link Scientific Domain to CMIP7:"
labels: ['delta', 'scientific_domain', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Link Scientific Domain to CMIP7
        
        Select scientific domains from WCRP-constants to make available in CMIP7.
        
        Scientific domains (realms) are initially defined in the [WCRP-constants repository](https://github.com/WCRP-CMIP/WCRP-constants). You can view existing domains at https://wcrp-cmip.github.io/WCRP-constants/scientific_domain/
        
        **If your scientific domain is not listed below**, you must first [register it in WCRP-constants](https://github.com/WCRP-CMIP/WCRP-constants/issues/new?template=scientific_domain.yml) and wait for it to be approved before linking it here.
        
        Once your scientific domain exists in WCRP-constants, use this form to make it available for use in CMIP7.
        
        ---
        
        **Currently registered in CMIP7:**
        

  - type: dropdown
    id: realm
    attributes:
      multiple: true
      label: Scientific Domain
      description: Select the scientific domains to add to CMIP7.
      options:
        - "aerosol"
        - "atmosphere"
        - "atmospheric_chemistry"
        - "land_ice"
        - "land_surface"
        - "ocean"
        - "ocean_biogeochemistry"
        - "sea_ice"
    validations:
      required: true

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
