name: Link Scientific Domain to CMIP7
description: Register a scientific domain (realm) for use in CMIP7
title: "Link Scientific Domain to CMIP7:"
labels: ['delta', 'scientific_domain', 'Review']
body:
  - type: dropdown
    id: realm
    attributes:
      multiple: true
      label: Scientific Domain
      description: |
        If your scientific domain is not listed below, you must first register it in the [WCRP-constants repository](https://wcrp-cmip.github.io/WCRP-constants/scientific_domain/) after which it should appear in the dropdown below.
        
        <details>
        <summary>Existing entries</summary>
        
        **Currently registered in CMIP7:**
        
        
        </details>
      options:
        - "aerosol"
        - "atmosphere"
        - "atmospheric_chemistry"
        - "land_ice"
        - "land_surface"
        - "ocean"
        - "ocean_biogeochemistry"
        - "sea_ice"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata [for internal use only]

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
