name: "New Review submission : Region"
description: Add region to CMIP7 CVs
title: "New Review submission : Region:"
labels: ['delta', 'region', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        This form appends the following region into the permitted CMIP7 Controlled Vocabularies list.
        
        The permitted set of values are defined in the WCRP constants repo. Regions are not yet in the constants repo - this is a CMIP7-specific CV.

  - type: dropdown
    id: region
    attributes:
      multiple: true
      label: Region
      description: Select the regions to add to CMIP7
      options:
        - "ant"
        - "glb"
        - "gre"
        - "nhem"
        - "shem"
    validations:
      required: true
