name: Link Region to CMIP7
description: Register a region for use in CMIP7
title: "Link Region to CMIP7:"
labels: ['delta', 'region', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Link Region to CMIP7
        
        Select regions from WCRP-constants to make available in CMIP7.
        
        Regions are initially defined in the [WCRP-constants repository](https://github.com/WCRP-CMIP/WCRP-constants). You can view existing regions at https://wcrp-cmip.github.io/WCRP-constants/region/
        
        **If your region is not listed below**, you must first [register it in WCRP-constants](https://github.com/WCRP-CMIP/WCRP-constants/issues/new?template=region.yml) and wait for it to be approved before linking it here.
        
        Once your region exists in WCRP-constants, use this form to make it available for use in CMIP7.
        
        ---
        
        **Currently registered in CMIP7:**
        

  - type: dropdown
    id: region
    attributes:
      multiple: true
      label: Region
      description: Select the regions to add to CMIP7.
      options:
        - "30s-90s"
        - "antarctica"
        - "arctic"
        - "global"
        - "greenland"
        - "limited-area"
        - "northern_hemisphere"
        - "shem"
        - "southern_hemisphere"
        - "tropics"
    validations:
      required: true

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
