name: "Add/Modify: Region"
description: Add region to CMIP7 CVs
title: "Add/Modify: Region: <Type region here>"
labels: ['delta', 'region', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        This form appends the following region into the permitted CMIP7 Controlled Vocabularies list.
        
        The permitted set of values are defined in the WCRP universal constants repo. Regions are not yet in the universal repo - this is a CMIP7-specific CV.

  - type: dropdown
    id: region
    attributes:
      multiple: true
      label: Region
      description: Select the regions to add to CMIP7
      options:
        - "ant"
        - "glb"
        - "gre"
        - "nhem"
        - "shem"
    validations:
      required: true
