name: Link Region to CMIP7
description: Register a region for use in CMIP7
title: "Link Region to CMIP7:"
labels: ['delta', 'region', 'Review']
body:
  - type: dropdown
    id: region
    attributes:
      multiple: true
      label: Region
      description: |
        If your region is not listed below, you must first register it in the [WCRP-constants repository](https://wcrp-cmip.github.io/WCRP-constants/region/) after which it should appear in the dropdown below.
        
        <details>
        <summary>Existing entries</summary>
        
        **Currently registered in CMIP7:**
        
        
        </details>
      options:
        - "30s-90s"
        - "antarctica"
        - "arctic"
        - "global"
        - "greenland"
        - "limited-area"
        - "northern_hemisphere"
        - "shem"
        - "southern_hemisphere"
        - "tropics"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata [for internal use only]

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
