name: "New Review submission : Source Type"
description: Add source type to CMIP7 CVs
title: "New Review submission : Source Type:"
labels: ['delta', 'source-type', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        This form appends the following source type into the permitted CMIP7 Controlled Vocabularies list.
        
        The permitted set of values are defined in the [WCRP constants repo](https://wcrp-cmip.github.io/WCRP-constants/source_type/). If your item is missing please [register here first](https://github.com/WCRP-CMIP/WCRP-constants/issues/new?template=source_type.yml) and wait a day after it has been confirmed for this script to be remade.

  - type: dropdown
    id: source_type
    attributes:
      multiple: true
      label: Source Type
      description: Select the source types to add to CMIP7
      options:
        - "AER"
        - "AGCM"
        - "AOGCM"
        - "BGC"
        - "CHEM"
        - "ISM"
        - "LAND"
        - "OGCM"
        - "RAD"
        - "SLAB"
        - "gridded_insitu"
        - "reanalysis"
        - "satellite_blended"
        - "satellite_retrieval"
    validations:
      required: true
