name: Link Source Type to CMIP7
description: Register a source type for use in CMIP7
title: "Link Source Type to CMIP7:"
labels: ['delta', 'source-type', 'Review']
body:
  - type: dropdown
    id: source_type
    attributes:
      multiple: true
      label: Source Type
      description: |
        If your source type is not listed below, you must first register it in the [WCRP-constants repository](https://wcrp-cmip.github.io/WCRP-constants/source_type/) after which it should appear in the dropdown below.
        
        <details>
        <summary>Existing entries</summary>
        
        **Currently registered in CMIP7:**
        
        
        </details>
      options:
        - "AER"
        - "AGCM"
        - "AOGCM"
        - "BGC"
        - "CHEM"
        - "ISM"
        - "LAND"
        - "OGCM"
        - "RAD"
        - "SLAB"
        - "gridded_insitu"
        - "reanalysis"
        - "satellite_blended"
        - "satellite_retrieval"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata [for internal use only]

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
