name: "New Review submission : Model/Source"
description: Register a climate model or data source for CMIP7
title: "New Review submission : Source:"
labels: ['delta', 'source', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## CMIP7 Model/Source Registration
        
        Register a climate model or data source for CMIP7.
        
        For CMIP7, this becomes the **source_id** in file metadata and directory structures.

  - type: input
    id: validation-key
    attributes:
      label: Source ID
      description: |
        The unique identifier for this model or data source.
        
        **Naming convention:**
        - Use lowercase letters, numbers, and hyphens
        - Include institution prefix (recommended)
        - Include model name and version
        - Examples: cnrm-esm2-1, hadgem3-gc31-mm, ukesm1-0-ll
        
        Note: This will become the @id and source_id in metadata.
      placeholder: "e.g., institution-model-version"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Model Description
      description: |
        Comprehensive description of the model or data source.
        
        **For models, describe:**
        - Overall model structure and components
        - Resolution characteristics
        - Key physics and parameterizations
        - Version history or relationship to other models
        
        **For obs/reanalysis, describe:**
        - Data source and collection methods
        - Processing and quality control
        - Spatial and temporal coverage
        - Version information
      placeholder: "Provide detailed description of the model/source..."
    validations:
      required: true

  - type: dropdown
    id: activity
    attributes:
      multiple: true
      label: Activity ID(s)
      description: |
        MIP activities this model/source will participate in.
        
        **For models**: Select all activities you plan to contribute to
        **For obs/reanalysis**: Select activities where this data will be used
        
        * Select Multiple *
      options:
        - "AerChemMIP"
        - "C4MIP"
        - "CFMIP"
        - "CMIP"
        - "DAMIP"
        - "DCPP"
        - "GeoMIP"
        - "HighResMIP"
        - "LMIP"
        - "PMIP"
        - "RFMIP"
        - "ScenarioMIP"
    validations:
      required: true

  - type: select
    id: cohort
    attributes:
      label: Cohort
      description: |
        Publication status or data availability.
        
        **Options:**
        - Published: Peer-reviewed model description exists
        - Registered: Model registered but paper in prep
        - Preliminary: Early development, may change
        
        **For obs/reanalysis:**
        - Published: Publicly available
        - Registered: Available with registration
        - Preliminary: Pre-release version
        
        * Select Multiple *
    validations:
      required: true

  - type: select
    id: institution
    attributes:
      label: Institution(s)
      description: |
        Institution(s) responsible for this model/source.
        
        Select all that apply for multi-institutional efforts.
        
        Institutions must be registered in the WCRP-universe repository.
        
        * Select Multiple *
    validations:
      required: true

  - type: select
    id: license_info
    attributes:
      label: License
      description: |
        Data license type.
        
        **Most common:**
        - cc-by-4.0: Creative Commons Attribution 4.0
        - cc-by-sa-4.0: Creative Commons Attribution-ShareAlike 4.0
        - cc0-1.0: Public domain dedication
        
        For obs/reanalysis, specify applicable license.
        
        * Select Multiple *
    validations:
      required: true

  - type: select
    id: model_documentation
    attributes:
      label: Model Documentation Reference
      description: Please register your EMD and then update this field.

  - type: markdown
    attributes:
      value: |
        ## Issue Handling Metadata
        
        These options control how the submission is processed.
        
        In most cases, these do not need to be changed.

  - type: dropdown
    id: issue_category
    attributes:
      label: Issue Type
      description: This is pre-set and cannot be changed.
      options:
        - "source"
      default: 0
    validations:
      required: true

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
