name: Link Source Type to CMIP7
description: Register a source type for use in CMIP7
title: "Link Source Type to CMIP7:"
labels: ['delta', 'source-type', 'Review']
body:
  - type: markdown
    attributes:
      value: |
        ## Link Source Type to CMIP7
        
        Select source types from WCRP-constants to make available in CMIP7.
        
        Source types are initially defined in the [WCRP-constants repository](https://github.com/WCRP-CMIP/WCRP-constants). You can view existing source types at https://wcrp-cmip.github.io/WCRP-constants/source_type/
        
        **If your source type is not listed below**, you must first [register it in WCRP-constants](https://github.com/WCRP-CMIP/WCRP-constants/issues/new?template=source_type.yml) and wait for it to be approved before linking it here.
        
        Once your source type exists in WCRP-constants, use this form to make it available for use in CMIP7.
        
        ---
        
        **Currently registered in CMIP7:**
        

  - type: dropdown
    id: source_type
    attributes:
      multiple: true
      label: Source Type
      description: Select the source types to add to CMIP7.
      options:
        - "AER"
        - "AGCM"
        - "AOGCM"
        - "BGC"
        - "CHEM"
        - "ISM"
        - "LAND"
        - "OGCM"
        - "RAD"
        - "SLAB"
        - "gridded_insitu"
        - "reanalysis"
        - "satellite_blended"
        - "satellite_retrieval"
    validations:
      required: true

  - type: dropdown
    id: issue_kind
    attributes:
      label: Issue Kind
      description: Select whether this is a new submission or modification of existing entry.
      options:
        - "New"
        - "Modify"
      default: 0
    validations:
      required: true
