name: ∆ src-data
description: Sync JSON and @context changes from src-data to production, and apply relevant documentation and summary updates

on:
  push:
    branches:
      - src-data
    paths:
      - '**/*.json'
      - '**/@context'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout production branch
      - name: Checkout production branch
        uses: actions/checkout@v4

      # Clean everything except docs and summaries in production
      - name: Remove everything except docs and summaries (production)
        run: |
          shopt -s extglob
          rm -rf !("docs"|"summaries"|"."|"..")

      # Checkout src-data branch to temp directory
      - name: Checkout src-data branch to temp
        uses: actions/checkout@v4
        with:
          ref: src-data
          path: temp-src

      - name: Copy new/updated JSON and @context files
        run: |
          rsync -av --exclude='docs' --exclude='summaries' temp-src/ .

      - name: Install cmipld
        uses: WCRP-CMIP/CMIPLD/actions/cmipld@main

      # Example: Run your data processing script here, or call an action
      # - name: Create Graph.jsonld
      #   run: |
      #     ./scripts/create-graph-jsonld.sh

      - name: Commit All
        uses: WCRP-CMIP/CMIPLD/actions/commit-all@main
        with:
          message: "Automated Content Update"

      - name: Push PR
        uses: WCRP-CMIP/CMIPLD/actions/pushpr@main
        with:
          branch: "production"
          message: "Automated CI parsing and update"
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-pages:
    needs: sync
    uses: WCRP-CMIP/CMIPLD/.github/workflows/pages.yml@main
    with:
      branch: production
      force: true
    secrets: inherit
