name: ∆ src-data
description: Sync JSON and @context changes from src-data to production, and apply relevant documentation and summary updates

on:
  push:
    branches:
      - src-data
    paths:
      - '**/*.json'
      - '**/@context'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:

      - name: Install cmipld
        id: install-cmipld
        uses: WCRP-CMIP/CMIPLD/actions/cmipld@main
        
      # Checkout production branch
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: production
          fetch-depth: 0

      # Clean everything except docs and summaries in production
      - name: Remove everything except docs and summaries (production)
        run: |
          shopt -s extglob
          rm -rf !("docs"|"summaries"|"."|"..")

      # Checkout src-data branch to temp directory
      - name: Checkout src-data branch to temp
        uses: actions/checkout@v4
        with:
          ref: src-data
          path: temp-src
          


      - name: Create graph files (aggregates)
        id: update-jsonld
        run: |
          update-jsonld

      # - name: Generate summaries
      #   id: gen-summary
      #   run: |
      #     generate_summary .github/GENERATE_SUMMARY/

          

      - name: Commit All
        uses: WCRP-CMIP/CMIPLD/actions/commit-all@main
        with:
          message: "Automated Content Update"

      - name: Push PR
        uses: WCRP-CMIP/CMIPLD/actions/pushpr@main
        with:
          branch: "production"
          message: "Automated CI parsing and update"
          token: ${{ secrets.GITHUB_TOKEN }}


            # Trigger (force) update of the Pages site via cmipld action
      - name: publish/update Pages site
        uses: WCRP-CMIP/CMIPLD/actions/pages.yml@main
        with:
          branch: production
          force: true
          secrets: inherit
          token: ${{ secrets.GITHUB_TOKEN }}
