fix Skip to content
Navigation Menu
WCRP-CMIPCMIP7-CVs
Type / to search
* Code
* Issues51
* Pull requests6
* Discussions
* Actions
* Projects
* Security
* Insights
* Settings
∆ src-data
∆ src-data #50
* 
* 
* Jobs
   * 
* 
* Run details
   * 
   * 
Workflow file for this run
.github/workflows/src-data-change.yml at c36ca29
name: ∆ src-datadescription: Sync JSON and @context changes from src-data to production, applying relevant updates. permissions: contents: write pages: write on: push: branches: - src-data paths: - '**/*.json' - '**/@context' workflow_dispatch: jobs: sync: runs-on: ubuntu-latest steps: - name: Checkout production branch uses: actions/checkout@v4 with: ref: production fetch-depth: 0 persist-credentials: true - name: Clean production except docs and summaries run: | shopt -s extglob dotglob echo ">>> Files that will be removed (everything except docs, summaries, .git, .github):" ls -A | awk '{ if ($0 != "docs" && $0 != "summaries" && $0 != ".git" && $0 != ".github") print $0 }' || true rm -rf -- !(docs|summaries|.git|.github) - name: Restore path from src-data branch uses: WCRP-CMIP/CMIPLD/actions/fetch_branch_path@main with: branch: "src-data" path: . remove: false - name: Debug — show git status and changed files run: | git config --global --add safe.directory "$GITHUB_WORKSPACE" || true echo "=== git status (porcelain) ===" git status --porcelain --untracked-files=all || true echo "=== changed files ===" git --no-pager diff --name-only || true echo "=== ls workspace ===" ls -la || true - name: Check for changes id: check_changes run: | git add -A if git diff --cached --quiet; then echo "no_changes=true" >> $GITHUB_OUTPUT echo "✅ No changes detected — skipping commit." else echo "no_changes=false" >> $GITHUB_OUTPUT echo "🔄 Changes detected — will commit." fi - name: Commit and Push Changes if: steps.check_changes.outputs.no_changes == 'false' uses: EndBug/add-and-commit@v9 with: add: '.' author_name: 'cmip-ipo' author_email: 'actions@wcrp-cmip.org' message: 'Clean file upload from src-data' branch: production push: true graph:
Check failure on line 79 in .github/workflows/src-data-change.yml
GitHub Actions/ ∆ src-data
Invalid workflow file

The workflow is not valid. .github/workflows/src-data-change.yml (Line: 79, Col: 3): Error calling workflow 'WCRP-CMIP/CMIPLD/.github/workflows/graph.yml@main'. The workflow is requesting 'actions: write', but is only allowed 'actions: none'.
uses: WCRP-CMIP/CMIPLD/.github/workflows/graph.yml@main needs: sync with: updated: false publish-pages: needs: - graph uses: WCRP-CMIP/CMIPLD/.github/workflows/pages.yml@main with: branch: production force: true secrets: token: ${{ secrets.GITHUB_TOKEN }}
Update src-data-change.yml · WCRP-CMIP/CMIP7-CVs@c36ca29

Looking at the error, the issue is that your workflow is trying to call a reusable workflow that requires actions: write permission, but your workflow only has actions: none permission.

The error occurs at line 79 where you're calling WCRP-CMIP/CMIPLD/.github/workflows/graph.yml@main, which needs actions: write permission but your workflow doesn't grant it.

Here's the fix - you need to add actions: write to your permissions section:


Failed to edit
Src-data-change
Let me first check what files are available and create the corrected workflow file:


Check the current directory structure
name: ∆ src-data
description: Sync JSON and @context changes from src-data to production, applying relevant updates.
permissions:
  contents: write
  pages: write
on:
  push:
    branches:
      - src-dataa
    paths:
      - '**/*.json'
      - '**/@context'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: production
          fetch-depth: 0
          persist-credentials: true
      - name: Clean production except docs and summaries
        run: |
          shopt -s extglob dotglob
          echo ">>> Files that will be removed (everything except docs, summaries, .git, .github):"
          ls -A | awk '{
            if ($0 != "docs" && $0 != "summaries" && $0 != ".git" && $0 != ".github") print $0
          }' || true
          rm -rf -- !(docs|summaries|.git|.github)
      - name: Restore path from src-data branch
        uses: WCRP-CMIP/CMIPLD/actions/fetch_branch_path@main
        with:
          branch: "src-data"
          path: .
          remove: false
      - name: Debug — show git status and changed files
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE" || true
          echo "=== git status (porcelain) ==="
          git status --porcelain --untracked-files=all || true
          echo "=== changed files ==="
          git --no-pager diff --name-only || true
          echo "=== ls workspace ==="
          ls -la || true
      - name: Check for changes
        id: check_changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            echo "✅ No changes detected — skipping commit."
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
            echo "🔄 Changes detected — will commit."
          fi
      - name: Commit and Push Changes
        if: steps.check_changes.outputs.no_changes == 'false'
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: 'cmip-ipo'
          author_email: 'actions@wcrp-cmip.org'
          message: 'Clean file upload from src-data'
          branch: production
          push: true
  graph:
    uses: WCRP-CMIP/CMIPLD/.github/workflows/graph.yml@main
    needs: sync
    with:
      updated: false
  publish-pages:
    needs:
      - graph
    uses: WCRP-CMIP/CMIPLD/.github/workflows/pages.yml@main
    with:
      branch: production
      force: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

I can see two issues in your workflow file:

Missing actions: write permission - This is causing the main error
Typo in branch name - You have src-dataa instead of src-data
Here's the corrected workflow file:


Create the corrected GitHub Actions workflow file with proper permissions and fixed branch name
src-data-change.yml
Summary of fixes:
Added actions: write permission - This resolves the main error where the reusable workflow graph.yml requires actions: write but wasn't granted it
Fixed the branch name typo - Changed src-dataa to src-data in the push trigger
The key issue was that when you call a reusable workflow (like WCRP-CMIP/CMIPLD/.github/workflows/graph.yml@main), that workflow may require certain permissions. The graph.yml workflow needs actions: write permission, so you must grant it in your calling workflow's permissions section.

View your corrected workflow file

Src data change
YML 







Src data change · YML
Copy

name: ∆ src-data
description: Sync JSON and @context changes from src-data to production, applying relevant updates.
permissions:
  contents: write
  pages: write
  actions: write
on:
  push:
    branches:
      - src-data
    paths:
      - '**/*.json'
      - '**/@context'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: production
          fetch-depth: 0
          persist-credentials: true
      - name: Clean production except docs and summaries
        run: |
          shopt -s extglob dotglob
          echo ">>> Files that will be removed (everything except docs, summaries, .git, .github):"
          ls -A | awk '{
            if ($0 != "docs" && $0 != "summaries" && $0 != ".git" && $0 != ".github") print $0
          }' || true
          rm -rf -- !(docs|summaries|.git|.github)
      - name: Restore path from src-data branch
        uses: WCRP-CMIP/CMIPLD/actions/fetch_branch_path@main
        with:
          branch: "src-data"
          path: .
          remove: false
      - name: Debug — show git status and changed files
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE" || true
          echo "=== git status (porcelain) ==="
          git status --porcelain --untracked-files=all || true
          echo "=== changed files ==="
          git --no-pager diff --name-only || true
          echo "=== ls workspace ==="
          ls -la || true
      - name: Check for changes
        id: check_changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            echo "✅ No changes detected — skipping commit."
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
            echo "🔄 Changes detected — will commit."
          fi
      - name: Commit and Push Changes
        if: steps.check_changes.outputs.no_changes == 'false'
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: 'cmip-ipo'
          author_email: 'actions@wcrp-cmip.org'
          message: 'Clean file upload from src-data'
          branch: production
          push: true
  graph:
    uses: WCRP-CMIP/CMIPLD/.github/workflows/graph.yml@main
    needs: sync
    with:
      updated: false
  publish-pages:
    needs:
      - graph
    uses: WCRP-CMIP/CMIPLD/.github/workflows/pages.yml@main
    with:
      branch: production
      force: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
