name: ∆ src-data
description: Sync JSON and @context changes from src-data to production, applying relevant updates.

permissions:
  contents: write
  pages: write
  actions: write
  id-token: write
on:
  push:
    branches:
      - src-data
    paths:
      - '**/*.json'
      - '**/@context'
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: production
          fetch-depth: 0
          persist-credentials: true
      - name: Clean production except docs and summaries
        run: |
          shopt -s extglob dotglob
          echo ">>> Files that will be removed (everything except docs, summaries, .git, .github):"
          ls -A | awk '{
            if ($0 != "docs" && $0 != "summaries" && $0 != ".git" && $0 != ".github") print $0
          }' || true
          rm -rf -- !(docs|summaries|.git|.github)
      - name: Restore path from src-data branch
        uses: WCRP-CMIP/CMIPLD/actions/fetch_branch_path@main
        with:
          branch: "src-data"
          path: .
          remove: false
      - name: Debug — show git status and changed files
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE" || true
          echo "=== git status (porcelain) ==="
          git status --porcelain --untracked-files=all || true
          echo "=== changed files ==="
          git --no-pager diff --name-only || true
          echo "=== ls workspace ==="
          ls -la || true
      - name: Check for changes
        id: check_changes
        run: |
          git add -A
          if git diff --cached --quiet; then
            echo "no_changes=true" >> $GITHUB_OUTPUT
            echo "✅ No changes detected — skipping commit."
          else
            echo "no_changes=false" >> $GITHUB_OUTPUT
            echo "🔄 Changes detected — will commit."
          fi
      - name: Commit and Push Changes
        if: steps.check_changes.outputs.no_changes == 'false'
        uses: EndBug/add-and-commit@v9
        with:
          add: '.'
          author_name: 'cmip-ipo'
          author_email: 'actions@wcrp-cmip.org'
          message: 'Clean file upload from src-data'
          branch: production
          push: true
  graph:
    uses: WCRP-CMIP/CMIPLD/.github/workflows/graph.yml@main
    needs: sync
    with:
      updated: false
  publish-pages:
    needs:
      - graph
    uses: WCRP-CMIP/CMIPLD/.github/workflows/pages.yml@main
    with:
      branch: production
      force: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
