name: ∆ src-data
description: Sync JSON and @context changes from src-data to production, applying relevant updates.

on:
  push:
    branches:
      - src-data
    paths:
      - '**/*.json'
      - '**/@context'
  workflow_dispatch:

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Clean production except docs and summaries
        run: |
          shopt -s extglob
          rm -rf !(docs|summaries|.git)



  sync:
    runs-on: ubuntu-latest
    needs: clean
    steps:
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: production

      - name: Restore path from remote action
        uses: WCRP-CMIP/CMIPLD/actions/fetch_branch_path@main
        with:
          branch: "src-data"
          path: .
          remove: false

  graph:
    uses: WCRP-CMIP/CMIPLD/.github/workflows/graph.yml@main
    needs: sync
    
  commit:
    runs-on: ubuntu-latest
    needs:
      - sync
      - graph
    steps:

      - name: Configure Git and Commit Changes
        run: |
          git config user.name "cmipipo-actions[bot]"
          git config user.email "technical@wcrp-cmip.org"
          git add .
          git commit -m "Automated Content Update" || echo "No changes to commit"

      - name: Push PR
        uses: WCRP-CMIP/CMIPLD/actions/pushpr@main
        with:
          branch: "production"
          message: "Automated JSONLD update"
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-pages:
    needs: commit
    uses: WCRP-CMIP/CMIPLD/.github/workflows/pages.yml@main
    with:
      branch: production
      force: true
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
