name: Sync JSON changes from src-data to production, and apply relevant documentation and summary updates

on:
  push:
    branches:
      - src-data
    paths:
      - '**/*.json'   # ✅ Trigger on any JSON file at any depth

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout production branch as the main workspace
      - name: Checkout production branch
        uses: actions/checkout@v4
        with:
          ref: src-data
          fetch-depth: 0

      
      - name: install cmipld
        id: install-cmipld
        uses: WCRP-CMIP/CMIPLD/actions/cmipld@main



      - name: Create graph files (aggregates)
        id: update-jsonld
        run: |
          update-jsonld 

    
      - name: Generate summaries
        id: gen-summary
        run: |
          generate_summary .github/GENERATE_SUMMARY/









          


      - name: Commit All
        uses: WCRP-CMIP/CMIPLD/actions/commit-all@main
        with:
          message: "Automated Content Update"
      
      - name: Push PR
        uses: WCRP-CMIP/CMIPLD/actions/pushpr@main
        with:
            branch: "src-data"
            message: "Automated CI parsing and update"
            token: ${{ secrets.GITHUB_TOKEN }}
