name: Close inactive issues

on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  low-priority-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 60
          days-before-issue-close: 30
          stale-issue-label: "stale"
          stale-issue-message: "This low-priority issue has been inactive for 60 days."
          close-issue-message: "This low-priority issue was closed after 30 more days of inactivity."
          only-issue-labels: "low-priority"
          exempt-issue-labels: "keep-open"
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  default-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-stale: 30
          days-before-issue-close: 14
          stale-issue-label: "stale"
          stale-issue-message: "This issue is stale after 30 days of inactivity."
          close-issue-message: "This issue was closed after 14 more days of inactivity."
          exempt-issue-labels: "low-priority,keep-open"
          days-before-pr-stale: -1
          days-before-pr-close: -1
          repo-token: ${{ secrets.GITHUB_TOKEN }}
