name: → workflows

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/**'
      - '.github/CONTRIBUTING.md'

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: 
          - src-data
          - docs
    
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ matrix.branch }}
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Copy files from main
        run: |
          mkdir -p .github/workflows
          git checkout main -- .github/workflows/
          git cat-file -e main:.github/CONTRIBUTING.md 2>/dev/null && \
            git checkout main -- .github/CONTRIBUTING.md || true
      
      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: '.github/'
          author_name: 'cmip-ipo'
          author_email: 'actions@wcrp-cmip.org'
          message: 'Sync .github files from main'
          branch: ${{ matrix.branch }}
          push: true
